### ISSUE TITLE
Component: Notification (item details)

### ISSUE THREAD

**Issue by brynjen** [knowit/teknologiradar#25]
Create design for a notification (https://www.figma.com/file/roJUFW8b3jmOSTpXSsV4AC/TechRadar?node-id=814%3A26863)
Should animate in on (top? bottom?) of transparent list (see Component: List for notifications task).
On Mobile, it should fill screen in portrait and lay on right in landscape. Limit of 300 chars for message.
On Web, on the right. Shrinking screen then horizontal shrink until fill screen.

Animate out by swiping on mobile if possible. Animate out when clicking close (animate with slide right).

**Comment by Jonas-C** [comment]
Dette er ikke en særlig tilgjengelig måte å vise frem informasjon på. Snacks/Toasts er generelt sett notorisk vanskelige å navigere seg til for tastatur- og skjermleserbrukere, samt at det fører til en del andre utfordringer.

**Comment by brynjen** [comment]
De er ikke ment som toasts/snackbar's, dårlig bruk av ordet notification. I den forstand at de viser kjapt info og forsvinner som regel av seg selv. Disse blir liggende til de er fjernet. Er derimot ikke uenig i at de blir kompliserte i forhold til universell utforming. Derimot usikker på om vi rekker en helt ny design runde til. Er det noe vi kan ignorere for v1 @Jonas-C ?

**Comment by Jonas-C** [comment]
Det er jo en ganske drastisk endring å ta tak i senere. Vi kan jo alltids ta i bruk dette nå, men hvis vi skal fronte et fokus på universell utforming synes jeg det er en bedre idé å finne et annet design.

**Comment by PauloSea** [comment]
Ok, da må vi finne en ny løsning.
Bra hvis dere kan komme med noen ideer/ forslag :)

**Comment by brynjen** [comment]
Pr diskusjon idag - vi endrer på det så den nå presenteres som en modal boks med bakgrunn istedet. Ref: https://www.figma.com/file/roJUFW8b3jmOSTpXSsV4AC/TechRadar?node-id=875%3A27257
