### ISSUE TITLE
Component: Footer

### ISSUE THREAD

**Issue by brynjen** [knowit/teknologiradar#28]
We need to implement the footer designet by Paulo. It will be used on both the intro screen as well as the main page. Remember support for mobile.

https://www.figma.com/file/roJUFW8b3jmOSTpXSsV4AC/TechRadar?node-id=766%3A26447

**Comment by janeivind** [comment]
Fant disse på vår egen hjemmeside, som kan brukes i footer.

[

![Image](https://user-images.githubusercontent.com/1169305/194235991-e635f32f-81cb-4d9f-806b-525c4b6e5c5a.svg)



![Image](https://user-images.githubusercontent.com/1169305/194236005-3ddd9946-d4a3-4565-96ef-aab942b958bc.svg)



![Image](https://user-images.githubusercontent.com/1169305/194236030-d0c46f7f-d9a5-4637-b288-a4a059cbdc4d.svg)

](url)

**Comment by swape** [comment]
jeg skal prøve å lage denne men kan noen assigne det til meg? lurer på om jeg ikke har nok rettigheter

**Comment by Jonas-C** [comment]
> jeg skal prøve å lage denne men kan noen assigne det til meg? lurer på om jeg ikke har nok rettigheter

Ordnet rettigheter til deg!

**Comment by swape** [comment]
Da trenger jeg bare all url'ene til alle de lenkene, til og med sosiale medie lenkene. @brynjen
